server:
  port: 8091
  error:
    include-message: always

spring:
  datasource:
    driverClassName: org.h2.Driver
    password: null
    username: sa
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        use_sql_comments: false
        format_sql: false
        show_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/